version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-name: astro
      - dependency-name: "@astrojs/*"
      - dependency-name: wrangler
    groups:
      astro:
        patterns:
          - astro
          - "@astrojs/*"
